# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyCloudHomeSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCloudHomeSDKDemo

  pod 'MyCloudHomeSDKObjc', :git => 'https://github.com/leshkoapps/MyCloudHomeSDKObjc', :commit => 'ef92a0801e6b0495c9eb2cb13e908ff34963e80f'

end
