# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyCloudHomeSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCloudHomeSDKDemo

  pod 'MyCloudHomeSDKObjc', :git => 'https://github.com/leshkoapps/MyCloudHomeSDKObjc', :commit => '5787647947727466e7f1dae223b275aa9a9b8a09'

end
