# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyCloudHomeSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCloudHomeSDKDemo

  pod 'MyCloudHomeSDKObjc', :git => 'https://github.com/leshkoapps/MyCloudHomeSDKObjc', :commit => '38b1b17d83a5210e6612e34aac6888625d66c997'

end
